---
- name: Mise à jour des Instances
  shell: "yum update -y"
  warn: false

- name: "Installation du serveur apache httpd et prise en charge SSL"
  yum:
          name: httpd, mod_ssl
          state: present
          update_cache: yes

- name: "Activation du service apache"
  service:
          name: httpd
          state: started
          enabled: yes

- name: "Installation des paquets PHP"
  include: "php7-install.yml"
  when: php_install|default(False)|bool

