---
- name: Mise à jour Système des Instances
  shell: "yum update -y"
  args:
      warn: no

- name: Installation httpd et prise en charge SSL
  yum:
          name: httpd, mod_ssl
          state: present
          update_cache: yes

- name: Copie du fichier de Configuration Apache personnalisé
  copy:
    src: httpd.conf
    dest: /etc/httpd/conf/httpd.conf

- name: Activation et Démarrage du service httpd
  service:
          name: httpd
          state: started
          enabled: yes

- name: Installation des compléments
  include: "php7-depots.yml"
  when: php_install|default(False)|bool

