---
- name: Telecharge et Installe le dernier paquet WordPress
  unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/html"
        remote_src: yes
        creates: "/var/www/html/wordpress"

- name: Changement groupe et user dossiers et fichiers
  file:
      path: /var/www
      owner: apache
      group: apache

- name: Modification permissions dossiers
  shell: "/usr/bin/find /var/www/html/wordpress/ -type d -exec chmod 750 {} \\;"

- name: Modification permissions fichiers
  shell: "/usr/bin/find /var/www/html/wordpress/ -type f -exec chmod 640 {} \\;"

